"""Init chat analytics schema

Revision ID: ac7d3b374168
Revises: 
Create Date: 2026-03-13 17:46:31.003374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac7d3b374168'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_nick', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('active', 'closed', 'archived')", name='ck_threads_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_threads_last_message_at', 'threads', ['last_message_at'], unique=False)
    op.create_index('ix_threads_status_created_at', 'threads', ['status', 'created_at'], unique=False)
    op.create_index('ix_threads_user_profile_created_at', 'threads', ['user_id', 'profile_id', 'created_at'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_nick', sa.String(length=255), nullable=False),
    sa.Column('intent', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'started'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('started', 'completed', 'failed', 'clarification_needed')", name='ck_agent_runs_status'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_status_created_at', 'agent_runs', ['status', 'created_at'], unique=False)
    op.create_index('ix_agent_runs_thread_created_at', 'agent_runs', ['thread_id', 'created_at'], unique=False)
    op.create_table('thread_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_nick', sa.String(length=255), nullable=False),
    sa.Column('changed_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('old_value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('title_updated', 'archived', 'restored', 'deleted')", name='ck_threads_history_event_type'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_threads_history_thread_created_at', 'thread_history', ['thread_id', 'created_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_run_id', 'messages', ['run_id'], unique=False)
    op.create_index('ix_messages_thread_created_at', 'messages', ['thread_id', 'created_at'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_nick', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('is_positive', sa.Boolean(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('is_negative', sa.Boolean(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_index('ix_messages_thread_created_at', table_name='messages')
    op.drop_index('ix_messages_run_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_threads_history_thread_created_at', table_name='thread_history')
    op.drop_table('thread_history')
    op.drop_index('ix_agent_runs_thread_created_at', table_name='agent_runs')
    op.drop_index('ix_agent_runs_status_created_at', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_threads_user_profile_created_at', table_name='threads')
    op.drop_index('ix_threads_status_created_at', table_name='threads')
    op.drop_index('ix_threads_last_message_at', table_name='threads')
    op.drop_table('threads')
    # ### end Alembic commands ###
