repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff-check

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: .venv/bin/python -m mypy app
        language: system
        pass_filenames: false
        types: [python]

      - id: pytest
        name: pytest
        entry: .venv/bin/python -m pytest
        language: system
        pass_filenames: false
        types: [python]
