"""Typed schemas for the SmartRest agent boundaries."""

from app.schemas.agent import AgentState, IntentType, RunStatus, ToolResponses
from app.schemas.base import SchemaModel
from app.schemas.calculations import (
    AverageCalculationSpec,
    CalculationFormula,
    CalculationRoundingMode,
    CalculationWarningCode,
    ComputeMetricsRequest,
    ComputeMetricsResponse,
    DeltaCalculationSpec,
    DerivedMetric,
    PercentChangeCalculationSpec,
    PerDayRateCalculationSpec,
    RatioCalculationSpec,
    SharePercentCalculationSpec,
    WeightedAverageCalculationSpec,
)
from app.schemas.reports import (
    ReportDefinition,
    ReportFilterKey,
    ReportFilters,
    ReportMetric,
    ReportRequest,
    ReportResult,
    ReportType,
)
from app.schemas.tools import (
    AccessStatus,
    GetReportDefinitionRequest,
    GetReportDefinitionResponse,
    ListReportsRequest,
    ListReportsResponse,
    ResolveScopeRequest,
    ResolveScopeResponse,
    RunReportRequest,
    RunReportResponse,
)

__all__ = [
    "AccessStatus",
    "AverageCalculationSpec",
    "AgentState",
    "CalculationFormula",
    "CalculationRoundingMode",
    "CalculationWarningCode",
    "ComputeMetricsRequest",
    "ComputeMetricsResponse",
    "DeltaCalculationSpec",
    "DerivedMetric",
    "GetReportDefinitionRequest",
    "GetReportDefinitionResponse",
    "IntentType",
    "ListReportsRequest",
    "ListReportsResponse",
    "PerDayRateCalculationSpec",
    "PercentChangeCalculationSpec",
    "ReportDefinition",
    "ReportFilterKey",
    "ReportFilters",
    "ReportType",
    "ReportMetric",
    "ReportRequest",
    "ReportResult",
    "ResolveScopeRequest",
    "ResolveScopeResponse",
    "RatioCalculationSpec",
    "RunReportRequest",
    "RunReportResponse",
    "RunStatus",
    "SchemaModel",
    "SharePercentCalculationSpec",
    "ToolResponses",
    "WeightedAverageCalculationSpec",
]
