"""init smartrest schema

Revision ID: d395f2ffc1d3
Revises: 
Create Date: 2026-03-26 15:14:54.349953

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd395f2ffc1d3'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS migrations")
    op.create_table('table_map',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('src_table', sa.String(length=255), nullable=False),
    sa.Column('dst_table', sa.String(length=255), nullable=False),
    sa.Column('src_pk', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_table_map')),
    schema='migrations'
    )
    op.create_table('profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('billing_status', sa.SmallInteger(), nullable=True),
    sa.Column('billing_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billing_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles'))
    )
    op.create_table('translate',
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('string', sa.String(length=255), nullable=False),
    sa.Column('en', sa.Text(), nullable=True),
    sa.Column('hy', sa.Text(), nullable=True),
    sa.Column('ru', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_translate'))
    )
    op.create_index(op.f('ix_translate_string'), 'translate', ['string'], unique=True)
    op.create_table('branches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_branches_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches'))
    )
    op.create_index(op.f('ix_branches_profile_id'), 'branches', ['profile_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('company', sa.BigInteger(), nullable=True),
    sa.Column('remote_id', sa.String(length=64), nullable=True),
    sa.Column('identification_document', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_clients_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    op.create_index(op.f('ix_clients_profile_id'), 'clients', ['profile_id'], unique=False)
    op.create_table('document_types',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('automatic', sa.Boolean(), nullable=True),
    sa.Column('order_in', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_document_types_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_types'))
    )
    op.create_index(op.f('ix_document_types_profile_id'), 'document_types', ['profile_id'], unique=False)
    op.create_table('material_category',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_material_category_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_category'))
    )
    op.create_index(op.f('ix_material_category_profile_id'), 'material_category', ['profile_id'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_measurements_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_measurements'))
    )
    op.create_index(op.f('ix_measurements_profile_id'), 'measurements', ['profile_id'], unique=False)
    op.create_table('column_map',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('table_map_id', sa.BigInteger(), nullable=False),
    sa.Column('src_column', sa.String(length=255), nullable=False),
    sa.Column('dst_column', sa.String(length=255), nullable=False),
    sa.Column('transform', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['table_map_id'], ['migrations.table_map.id'], name=op.f('fk_column_map_table_map_id_table_map'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_column_map')),
    schema='migrations'
    )
    op.create_index(op.f('ix_migrations_column_map_table_map_id'), 'column_map', ['table_map_id'], unique=False, schema='migrations')
    op.create_table('staff',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('salary_value', sa.String(length=255), nullable=True),
    sa.Column('dismission_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_staff_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff'))
    )
    op.create_index(op.f('ix_staff_profile_id'), 'staff', ['profile_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('reports', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_users_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index(op.f('ix_users_profile_id'), 'users', ['profile_id'], unique=False)
    op.create_table('break_points',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_break_points_branch_id_branches')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_break_points_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_break_points'))
    )
    op.create_index(op.f('ix_break_points_branch_id'), 'break_points', ['branch_id'], unique=False)
    op.create_index(op.f('ix_break_points_profile_id'), 'break_points', ['profile_id'], unique=False)
    op.create_table('cashboxes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.Column('cash_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('modify_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('set_default', sa.String(length=16), server_default=sa.text("'false'"), nullable=True),
    sa.Column('cashbox_name', sa.String(length=256), nullable=True),
    sa.Column('cashbox_name_ru', sa.String(length=256), nullable=True),
    sa.Column('cashbox_name_en', sa.String(length=256), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('is_bank', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('is_card', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('print_fiscal', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_cashboxes_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_cashboxes_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cashboxes'))
    )
    op.create_index(op.f('ix_cashboxes_branch_id'), 'cashboxes', ['branch_id'], unique=False)
    op.create_index(op.f('ix_cashboxes_profile_id'), 'cashboxes', ['profile_id'], unique=False)
    op.create_table('client_cards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('card_number', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Boolean(), nullable=True),
    sa.Column('percent', sa.String(length=16), nullable=True),
    sa.Column('balance', sa.SmallInteger(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remote_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_cards_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_client_cards_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_cards'))
    )
    op.create_index(op.f('ix_client_cards_client_id'), 'client_cards', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_cards_profile_id'), 'client_cards', ['profile_id'], unique=False)
    op.create_table('document_type_template',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('document_type_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], name=op.f('fk_document_type_template_document_type_id_document_types')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_document_type_template_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_type_template'))
    )
    op.create_index(op.f('ix_document_type_template_document_type_id'), 'document_type_template', ['document_type_id'], unique=False)
    op.create_index(op.f('ix_document_type_template_profile_id'), 'document_type_template', ['profile_id'], unique=False)
    op.create_table('halls',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('floor_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_halls_branch_id_branches')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_halls_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_halls'))
    )
    op.create_index(op.f('ix_halls_branch_id'), 'halls', ['branch_id'], unique=False)
    op.create_index(op.f('ix_halls_profile_id'), 'halls', ['profile_id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_logs_branch_id_branches')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_logs_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs'))
    )
    op.create_index(op.f('ix_logs_branch_id'), 'logs', ['branch_id'], unique=False)
    op.create_index(op.f('ix_logs_date'), 'logs', ['date'], unique=False)
    op.create_index(op.f('ix_logs_profile_id'), 'logs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_logs_user_id'), 'logs', ['user_id'], unique=False)
    op.create_table('material_category_language',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('language_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('material_category_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['material_category_id'], ['material_category.id'], name=op.f('fk_material_category_language_material_category_id_material_category')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_material_category_language_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_category_language'))
    )
    op.create_index(op.f('ix_material_category_language_material_category_id'), 'material_category_language', ['material_category_id'], unique=False)
    op.create_index(op.f('ix_material_category_language_profile_id'), 'material_category_language', ['profile_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('material_category_id', sa.BigInteger(), nullable=True),
    sa.Column('semi_finished', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('useful_weight', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['material_category_id'], ['material_category.id'], name=op.f('fk_materials_material_category_id_material_category')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_materials_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials'))
    )
    op.create_index(op.f('ix_materials_material_category_id'), 'materials', ['material_category_id'], unique=False)
    op.create_index(op.f('ix_materials_profile_id'), 'materials', ['profile_id'], unique=False)
    op.create_table('measurements_lng',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('language_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('unit_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_measurements_lng_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['measurements.id'], name=op.f('fk_measurements_lng_unit_id_measurements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_measurements_lng'))
    )
    op.create_index(op.f('ix_measurements_lng_profile_id'), 'measurements_lng', ['profile_id'], unique=False)
    op.create_index(op.f('ix_measurements_lng_unit_id'), 'measurements_lng', ['unit_id'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('modifier', sa.String(length=255), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_stores_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_stores_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores'))
    )
    op.create_index(op.f('ix_stores_branch_id'), 'stores', ['branch_id'], unique=False)
    op.create_index(op.f('ix_stores_profile_id'), 'stores', ['profile_id'], unique=False)
    op.create_table('material_content',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=True),
    sa.Column('unit_id', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('min_quantity', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('product_balance', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('pre_pack_mass', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_material_content_material_id_materials')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_material_content_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['measurements.id'], name=op.f('fk_material_content_unit_id_measurements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_content'))
    )
    op.create_index(op.f('ix_material_content_material_id'), 'material_content', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_content_profile_id'), 'material_content', ['profile_id'], unique=False)
    op.create_index(op.f('ix_material_content_unit_id'), 'material_content', ['unit_id'], unique=False)
    op.create_table('material_language',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('language_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('material_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_material_language_material_id_materials')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_material_language_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_language'))
    )
    op.create_index(op.f('ix_material_language_material_id'), 'material_language', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_language_profile_id'), 'material_language', ['profile_id'], unique=False)
    op.create_table('menu_place',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('title_ru', sa.String(length=255), nullable=True),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_menu_place_branch_id_branches')),
    sa.ForeignKeyConstraint(['profile'], ['profiles.id'], name=op.f('fk_menu_place_profile_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_menu_place_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_place'))
    )
    op.create_index(op.f('ix_menu_place_branch_id'), 'menu_place', ['branch_id'], unique=False)
    op.create_index(op.f('ix_menu_place_profile'), 'menu_place', ['profile'], unique=False)
    op.create_table('store_language',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('language_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_store_language_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_store_language_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_language'))
    )
    op.create_index(op.f('ix_store_language_profile_id'), 'store_language', ['profile_id'], unique=False)
    op.create_table('tables',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('room_table_name', sa.String(length=255), nullable=True),
    sa.Column('hall_id', sa.BigInteger(), nullable=True),
    sa.Column('delivery', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('service_commissions_type', sa.String(length=64), nullable=True),
    sa.Column('service_commissions_value', sa.Text(), nullable=True),
    sa.Column('max_people', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('hotel_room_status', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_tables_branch_id_branches')),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], name=op.f('fk_tables_hall_id_halls')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_tables_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tables'))
    )
    op.create_index(op.f('ix_tables_branch_id'), 'tables', ['branch_id'], unique=False)
    op.create_index(op.f('ix_tables_hall_id'), 'tables', ['hall_id'], unique=False)
    op.create_index(op.f('ix_tables_profile_id'), 'tables', ['profile_id'], unique=False)
    op.create_table('fifo_state',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_fifo_state_branch_id_branches')),
    sa.ForeignKeyConstraint(['item_id'], ['material_content.id'], name=op.f('fk_fifo_state_item_id_material_content')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_fifo_state_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_fifo_state_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fifo_state'))
    )
    op.create_index(op.f('ix_fifo_state_branch_id'), 'fifo_state', ['branch_id'], unique=False)
    op.create_index(op.f('ix_fifo_state_profile_id'), 'fifo_state', ['profile_id'], unique=False)
    op.create_table('menu_group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile', sa.BigInteger(), nullable=False),
    sa.Column('place', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('title_ru', sa.String(length=255), nullable=True),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_menu_group_branch_id_branches')),
    sa.ForeignKeyConstraint(['place'], ['menu_place.id'], name=op.f('fk_menu_group_place_menu_place')),
    sa.ForeignKeyConstraint(['profile'], ['profiles.id'], name=op.f('fk_menu_group_profile_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_group'))
    )
    op.create_index(op.f('ix_menu_group_branch_id'), 'menu_group', ['branch_id'], unique=False)
    op.create_index(op.f('ix_menu_group_place'), 'menu_group', ['place'], unique=False)
    op.create_index(op.f('ix_menu_group_profile'), 'menu_group', ['profile'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_order_uniq_id', sa.String(length=64), nullable=True),
    sa.Column('room_table_id', sa.BigInteger(), nullable=True),
    sa.Column('profile_staff_id', sa.BigInteger(), nullable=True),
    sa.Column('room_table_status', sa.String(length=64), nullable=True),
    sa.Column('order_create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_id', sa.BigInteger(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('table_commissions_type', sa.String(length=64), nullable=True),
    sa.Column('table_commissions_value', sa.Text(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('sale', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('payed', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('payment_status', sa.String(length=64), nullable=True),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tip', sa.Integer(), nullable=True),
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('final_total', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('time_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fix_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('clients_count', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.SmallInteger(), nullable=True),
    sa.Column('terminate_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type_id', sa.SmallInteger(), nullable=True),
    sa.Column('delivery_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('commission_total', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cashbox_id', sa.BigInteger(), nullable=True),
    sa.Column('hourly_pay_without_product', sa.Boolean(), nullable=True),
    sa.Column('is_delivery', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('discounted_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('sale_description', sa.Text(), nullable=True),
    sa.Column('order_type', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_orders_branch_id_branches')),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashboxes.id'], name=op.f('fk_orders_cashbox_id_cashboxes')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_orders_client_id_clients')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_orders_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_staff_id'], ['staff.id'], name=op.f('fk_orders_profile_staff_id_staff')),
    sa.ForeignKeyConstraint(['room_table_id'], ['tables.id'], name=op.f('fk_orders_room_table_id_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('profile_order_uniq_id', name=op.f('uq_orders_profile_order_uniq_id'))
    )
    op.create_index(op.f('ix_orders_branch_id'), 'orders', ['branch_id'], unique=False)
    op.create_index(op.f('ix_orders_client_id'), 'orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_orders_order_create_date'), 'orders', ['order_create_date'], unique=False)
    op.create_index('ix_orders_profile_date_paid', 'orders', ['profile_id', 'order_create_date', 'payment_status', 'payed', 'branch_id'], unique=False)
    op.create_index(op.f('ix_orders_profile_id'), 'orders', ['profile_id'], unique=False)
    op.create_index(op.f('ix_orders_profile_staff_id'), 'orders', ['profile_staff_id'], unique=False)
    op.create_index(op.f('ix_orders_room_table_id'), 'orders', ['room_table_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('type_id', sa.BigInteger(), nullable=True),
    sa.Column('status_id', sa.SmallInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('back_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('identification_number', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_documents_branch_id_branches')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_documents_order_id_orders')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_documents_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['document_types.id'], name=op.f('fk_documents_type_id_document_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_branch_id'), 'documents', ['branch_id'], unique=False)
    op.create_index(op.f('ix_documents_order_id'), 'documents', ['order_id'], unique=False)
    op.create_index(op.f('ix_documents_profile_id'), 'documents', ['profile_id'], unique=False)
    op.create_index(op.f('ix_documents_type_id'), 'documents', ['type_id'], unique=False)
    op.create_table('fiscal_receipt',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('report_type', sa.BigInteger(), nullable=True),
    sa.Column('report_start', sa.BigInteger(), nullable=True),
    sa.Column('report_end', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.BigInteger(), nullable=True),
    sa.Column('order_prepayment', sa.Boolean(), nullable=True),
    sa.Column('order_history_id', sa.BigInteger(), nullable=True),
    sa.Column('return_receipt_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_fiscal_receipt_order_id_orders')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_fiscal_receipt_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fiscal_receipt'))
    )
    op.create_index(op.f('ix_fiscal_receipt_order_id'), 'fiscal_receipt', ['order_id'], unique=False)
    op.create_index(op.f('ix_fiscal_receipt_profile_id'), 'fiscal_receipt', ['profile_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile', sa.BigInteger(), nullable=False),
    sa.Column('group', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('check_place', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('barcode', sa.String(length=128), nullable=True),
    sa.Column('frozen', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('suspended', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('suspend_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activate_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('hdm_name', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_menu_items_branch_id_branches')),
    sa.ForeignKeyConstraint(['group'], ['menu_group.id'], name=op.f('fk_menu_items_group_menu_group')),
    sa.ForeignKeyConstraint(['profile'], ['profiles.id'], name=op.f('fk_menu_items_profile_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_items'))
    )
    op.create_index(op.f('ix_menu_items_branch_id'), 'menu_items', ['branch_id'], unique=False)
    op.create_index(op.f('ix_menu_items_group'), 'menu_items', ['group'], unique=False)
    op.create_index(op.f('ix_menu_items_profile'), 'menu_items', ['profile'], unique=False)
    op.create_table('order_payment_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('payed', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=True),
    sa.Column('cashbox_id', sa.BigInteger(), nullable=True),
    sa.Column('card_id', sa.BigInteger(), nullable=True),
    sa.Column('cashbox_history_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['client_cards.id'], name=op.f('fk_order_payment_history_card_id_client_cards')),
    sa.ForeignKeyConstraint(['cashbox_id'], ['cashboxes.id'], name=op.f('fk_order_payment_history_cashbox_id_cashboxes')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_payment_history_order_id_orders')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_order_payment_history_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_payment_history'))
    )
    op.create_index(op.f('ix_order_payment_history_order_id'), 'order_payment_history', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_payment_history_profile_id'), 'order_payment_history', ['profile_id'], unique=False)
    op.create_table('clients_cards_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('card_code', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('menu_item_id', sa.BigInteger(), nullable=True),
    sa.Column('menu_item_count', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('menu_item_balance', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('menu_item_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('room_table_order_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('bonus_id', sa.BigInteger(), nullable=True),
    sa.Column('bonus_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_clients_cards_history_branch_id_branches')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_clients_cards_history_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_clients_cards_history_menu_item_id_menu_items')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_clients_cards_history_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_table_order_id'], ['orders.id'], name=op.f('fk_clients_cards_history_room_table_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients_cards_history'))
    )
    op.create_index(op.f('ix_clients_cards_history_branch_id'), 'clients_cards_history', ['branch_id'], unique=False)
    op.create_index(op.f('ix_clients_cards_history_client_id'), 'clients_cards_history', ['client_id'], unique=False)
    op.create_index(op.f('ix_clients_cards_history_create_date'), 'clients_cards_history', ['create_date'], unique=False)
    op.create_index(op.f('ix_clients_cards_history_menu_item_id'), 'clients_cards_history', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_clients_cards_history_profile_id'), 'clients_cards_history', ['profile_id'], unique=False)
    op.create_index(op.f('ix_clients_cards_history_room_table_order_id'), 'clients_cards_history', ['room_table_order_id'], unique=False)
    op.create_table('document_contents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('material_content_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity_in', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('quantity_out', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('referer_id', sa.BigInteger(), nullable=True),
    sa.Column('fifo_state_id', sa.BigInteger(), nullable=True),
    sa.Column('useful_weight_quantity', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('st_balance_create_status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_document_contents_branch_id_branches')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_contents_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fifo_state_id'], ['fifo_state.id'], name=op.f('fk_document_contents_fifo_state_id_fifo_state')),
    sa.ForeignKeyConstraint(['material_content_id'], ['material_content.id'], name=op.f('fk_document_contents_material_content_id_material_content')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_document_contents_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_document_contents_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_contents'))
    )
    op.create_index(op.f('ix_document_contents_branch_id'), 'document_contents', ['branch_id'], unique=False)
    op.create_index(op.f('ix_document_contents_document_id'), 'document_contents', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_contents_fifo_state_id'), 'document_contents', ['fifo_state_id'], unique=False)
    op.create_index(op.f('ix_document_contents_material_content_id'), 'document_contents', ['material_content_id'], unique=False)
    op.create_index(op.f('ix_document_contents_profile_id'), 'document_contents', ['profile_id'], unique=False)
    op.create_table('fiscal_receipt_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('receipt_id', sa.BigInteger(), nullable=True),
    sa.Column('rseq', sa.BigInteger(), nullable=True),
    sa.Column('crn', sa.String(length=64), nullable=True),
    sa.Column('sn', sa.String(length=64), nullable=True),
    sa.Column('tin', sa.String(length=64), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fiscal', sa.String(length=64), nullable=True),
    sa.Column('total', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('change', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_fiscal_receipt_history_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_id'], ['fiscal_receipt.id'], name=op.f('fk_fiscal_receipt_history_receipt_id_fiscal_receipt')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fiscal_receipt_history'))
    )
    op.create_index(op.f('ix_fiscal_receipt_history_profile_id'), 'fiscal_receipt_history', ['profile_id'], unique=False)
    op.create_index(op.f('ix_fiscal_receipt_history_receipt_id'), 'fiscal_receipt_history', ['receipt_id'], unique=False)
    op.create_table('menu_item_content',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile', sa.BigInteger(), nullable=False),
    sa.Column('menu_item', sa.BigInteger(), nullable=True),
    sa.Column('store_item', sa.BigInteger(), nullable=True),
    sa.Column('store_item_count', sa.BigInteger(), nullable=True),
    sa.Column('package_id', sa.BigInteger(), nullable=True),
    sa.Column('visibility', sa.Boolean(), nullable=True),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('suspended', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_menu_item_content_branch_id_branches')),
    sa.ForeignKeyConstraint(['menu_item'], ['menu_items.id'], name=op.f('fk_menu_item_content_menu_item_menu_items')),
    sa.ForeignKeyConstraint(['profile'], ['profiles.id'], name=op.f('fk_menu_item_content_profile_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_menu_item_content_store_id_stores')),
    sa.ForeignKeyConstraint(['store_item'], ['material_content.id'], name=op.f('fk_menu_item_content_store_item_material_content')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_content'))
    )
    op.create_index(op.f('ix_menu_item_content_branch_id'), 'menu_item_content', ['branch_id'], unique=False)
    op.create_index(op.f('ix_menu_item_content_menu_item'), 'menu_item_content', ['menu_item'], unique=False)
    op.create_index(op.f('ix_menu_item_content_profile'), 'menu_item_content', ['profile'], unique=False)
    op.create_index(op.f('ix_menu_item_content_store_item'), 'menu_item_content', ['store_item'], unique=False)
    op.create_table('order_content_removed',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('room_table_order_id', sa.BigInteger(), nullable=True),
    sa.Column('suborder_id', sa.BigInteger(), nullable=True),
    sa.Column('profile_menu_item_id', sa.BigInteger(), nullable=True),
    sa.Column('profile_menu_item_count', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remove_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('add_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_order_content_removed_branch_id_branches')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_order_content_removed_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_menu_item_id'], ['menu_items.id'], name=op.f('fk_order_content_removed_profile_menu_item_id_menu_items')),
    sa.ForeignKeyConstraint(['room_table_order_id'], ['orders.id'], name=op.f('fk_order_content_removed_room_table_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_content_removed'))
    )
    op.create_index(op.f('ix_order_content_removed_branch_id'), 'order_content_removed', ['branch_id'], unique=False)
    op.create_index(op.f('ix_order_content_removed_profile_id'), 'order_content_removed', ['profile_id'], unique=False)
    op.create_index(op.f('ix_order_content_removed_profile_menu_item_id'), 'order_content_removed', ['profile_menu_item_id'], unique=False)
    op.create_index(op.f('ix_order_content_removed_room_table_order_id'), 'order_content_removed', ['room_table_order_id'], unique=False)
    op.create_table('order_contents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('room_table_order_id', sa.BigInteger(), nullable=False),
    sa.Column('subtable_id', sa.BigInteger(), nullable=True),
    sa.Column('suborder_id', sa.BigInteger(), nullable=True),
    sa.Column('profile_menu_item_id', sa.BigInteger(), nullable=True),
    sa.Column('profile_menu_item_count', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('item_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cashback_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('done', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('product_sale', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('staff_id', sa.BigInteger(), nullable=True),
    sa.Column('order_in', sa.SmallInteger(), nullable=True),
    sa.Column('e_marks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_order_contents_branch_id_branches')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_order_contents_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_menu_item_id'], ['menu_items.id'], name=op.f('fk_order_contents_profile_menu_item_id_menu_items')),
    sa.ForeignKeyConstraint(['room_table_order_id'], ['orders.id'], name=op.f('fk_order_contents_room_table_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_order_contents_staff_id_staff')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_contents'))
    )
    op.create_index(op.f('ix_order_contents_branch_id'), 'order_contents', ['branch_id'], unique=False)
    op.create_index(op.f('ix_order_contents_create_date'), 'order_contents', ['create_date'], unique=False)
    op.create_index('ix_order_contents_menu_item', 'order_contents', ['profile_menu_item_id'], unique=False)
    op.create_index('ix_order_contents_order', 'order_contents', ['room_table_order_id'], unique=False)
    op.create_index(op.f('ix_order_contents_profile_id'), 'order_contents', ['profile_id'], unique=False)
    op.create_index(op.f('ix_order_contents_profile_menu_item_id'), 'order_contents', ['profile_menu_item_id'], unique=False)
    op.create_index(op.f('ix_order_contents_room_table_order_id'), 'order_contents', ['room_table_order_id'], unique=False)
    op.create_index(op.f('ix_order_contents_staff_id'), 'order_contents', ['staff_id'], unique=False)
    op.create_table('balance_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('original_create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('material_id', sa.BigInteger(), nullable=True),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('type_id', sa.SmallInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity_in', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('quantity_out', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('balance', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('order_content_id', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('document_content_id', sa.BigInteger(), nullable=True),
    sa.Column('useful_weight_quantity', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('fix_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('fix_balance', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_balance_history_branch_id_branches')),
    sa.ForeignKeyConstraint(['document_content_id'], ['document_contents.id'], name=op.f('fk_balance_history_document_content_id_document_contents')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_balance_history_document_id_documents')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_balance_history_material_id_materials')),
    sa.ForeignKeyConstraint(['order_content_id'], ['order_contents.id'], name=op.f('fk_balance_history_order_content_id_order_contents')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_balance_history_order_id_orders')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_balance_history_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_balance_history_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_balance_history'))
    )
    op.create_index(op.f('ix_balance_history_branch_id'), 'balance_history', ['branch_id'], unique=False)
    op.create_index(op.f('ix_balance_history_document_content_id'), 'balance_history', ['document_content_id'], unique=False)
    op.create_index(op.f('ix_balance_history_document_id'), 'balance_history', ['document_id'], unique=False)
    op.create_index(op.f('ix_balance_history_material_id'), 'balance_history', ['material_id'], unique=False)
    op.create_index(op.f('ix_balance_history_order_content_id'), 'balance_history', ['order_content_id'], unique=False)
    op.create_index(op.f('ix_balance_history_order_id'), 'balance_history', ['order_id'], unique=False)
    op.create_index(op.f('ix_balance_history_profile_id'), 'balance_history', ['profile_id'], unique=False)
    op.create_table('fifo_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('state_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity_in', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('quantity_out', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('document_content_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('order_content_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('changed', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_fifo_history_branch_id_branches')),
    sa.ForeignKeyConstraint(['document_content_id'], ['document_contents.id'], name=op.f('fk_fifo_history_document_content_id_document_contents')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_fifo_history_document_id_documents')),
    sa.ForeignKeyConstraint(['order_content_id'], ['order_contents.id'], name=op.f('fk_fifo_history_order_content_id_order_contents')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_fifo_history_order_id_orders')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_fifo_history_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['fifo_state.id'], name=op.f('fk_fifo_history_state_id_fifo_state')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fifo_history'))
    )
    op.create_index(op.f('ix_fifo_history_branch_id'), 'fifo_history', ['branch_id'], unique=False)
    op.create_index(op.f('ix_fifo_history_document_content_id'), 'fifo_history', ['document_content_id'], unique=False)
    op.create_index(op.f('ix_fifo_history_document_id'), 'fifo_history', ['document_id'], unique=False)
    op.create_index(op.f('ix_fifo_history_order_content_id'), 'fifo_history', ['order_content_id'], unique=False)
    op.create_index(op.f('ix_fifo_history_order_id'), 'fifo_history', ['order_id'], unique=False)
    op.create_index(op.f('ix_fifo_history_profile_id'), 'fifo_history', ['profile_id'], unique=False)
    op.create_index(op.f('ix_fifo_history_state_id'), 'fifo_history', ['state_id'], unique=False)
    op.create_table('moved_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('new_order_id', sa.BigInteger(), nullable=True),
    sa.Column('order_uniq_id', sa.String(length=64), nullable=True),
    sa.Column('new_order_uniq_id', sa.String(length=64), nullable=True),
    sa.Column('content_id', sa.BigInteger(), nullable=True),
    sa.Column('menu_item_id', sa.BigInteger(), nullable=True),
    sa.Column('menu_item_count', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('table_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_moved_items_branch_id_branches')),
    sa.ForeignKeyConstraint(['content_id'], ['order_contents.id'], name=op.f('fk_moved_items_content_id_order_contents')),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_moved_items_menu_item_id_menu_items')),
    sa.ForeignKeyConstraint(['new_order_id'], ['orders.id'], name=op.f('fk_moved_items_new_order_id_orders')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_moved_items_order_id_orders')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_moved_items_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('fk_moved_items_table_id_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moved_items'))
    )
    op.create_index(op.f('ix_moved_items_branch_id'), 'moved_items', ['branch_id'], unique=False)
    op.create_index(op.f('ix_moved_items_content_id'), 'moved_items', ['content_id'], unique=False)
    op.create_index(op.f('ix_moved_items_menu_item_id'), 'moved_items', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_moved_items_new_order_id'), 'moved_items', ['new_order_id'], unique=False)
    op.create_index(op.f('ix_moved_items_order_id'), 'moved_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_moved_items_profile_id'), 'moved_items', ['profile_id'], unique=False)
    op.create_index(op.f('ix_moved_items_table_id'), 'moved_items', ['table_id'], unique=False)
    op.create_table('profiles_room_table_order_package_components',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('room_table_order_content_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_menu_item_id', sa.BigInteger(), nullable=True),
    sa.Column('profile_menu_item_count', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('item_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_profiles_room_table_order_package_components_branch_id_branches')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_profiles_room_table_order_package_components_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_menu_item_id'], ['menu_items.id'], name=op.f('fk_profiles_room_table_order_package_components_profile_menu_item_id_menu_items')),
    sa.ForeignKeyConstraint(['room_table_order_content_id'], ['order_contents.id'], name=op.f('fk_profiles_room_table_order_package_components_room_table_order_content_id_order_contents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles_room_table_order_package_components'))
    )
    op.create_index(op.f('ix_profiles_room_table_order_package_components_branch_id'), 'profiles_room_table_order_package_components', ['branch_id'], unique=False)
    op.create_index(op.f('ix_profiles_room_table_order_package_components_profile_menu_item_id'), 'profiles_room_table_order_package_components', ['profile_menu_item_id'], unique=False)
    op.create_index(op.f('ix_profiles_room_table_order_package_components_profile_id'), 'profiles_room_table_order_package_components', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profiles_room_table_order_package_components_room_table_order_content_id'), 'profiles_room_table_order_package_components', ['room_table_order_content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_room_table_order_package_components_room_table_order_content_id'), table_name='profiles_room_table_order_package_components')
    op.drop_index(op.f('ix_profiles_room_table_order_package_components_profile_id'), table_name='profiles_room_table_order_package_components')
    op.drop_index(op.f('ix_profiles_room_table_order_package_components_profile_menu_item_id'), table_name='profiles_room_table_order_package_components')
    op.drop_index(op.f('ix_profiles_room_table_order_package_components_branch_id'), table_name='profiles_room_table_order_package_components')
    op.drop_table('profiles_room_table_order_package_components')
    op.drop_index(op.f('ix_moved_items_table_id'), table_name='moved_items')
    op.drop_index(op.f('ix_moved_items_profile_id'), table_name='moved_items')
    op.drop_index(op.f('ix_moved_items_order_id'), table_name='moved_items')
    op.drop_index(op.f('ix_moved_items_new_order_id'), table_name='moved_items')
    op.drop_index(op.f('ix_moved_items_menu_item_id'), table_name='moved_items')
    op.drop_index(op.f('ix_moved_items_content_id'), table_name='moved_items')
    op.drop_index(op.f('ix_moved_items_branch_id'), table_name='moved_items')
    op.drop_table('moved_items')
    op.drop_index(op.f('ix_fifo_history_state_id'), table_name='fifo_history')
    op.drop_index(op.f('ix_fifo_history_profile_id'), table_name='fifo_history')
    op.drop_index(op.f('ix_fifo_history_order_id'), table_name='fifo_history')
    op.drop_index(op.f('ix_fifo_history_order_content_id'), table_name='fifo_history')
    op.drop_index(op.f('ix_fifo_history_document_id'), table_name='fifo_history')
    op.drop_index(op.f('ix_fifo_history_document_content_id'), table_name='fifo_history')
    op.drop_index(op.f('ix_fifo_history_branch_id'), table_name='fifo_history')
    op.drop_table('fifo_history')
    op.drop_index(op.f('ix_balance_history_profile_id'), table_name='balance_history')
    op.drop_index(op.f('ix_balance_history_order_id'), table_name='balance_history')
    op.drop_index(op.f('ix_balance_history_order_content_id'), table_name='balance_history')
    op.drop_index(op.f('ix_balance_history_material_id'), table_name='balance_history')
    op.drop_index(op.f('ix_balance_history_document_id'), table_name='balance_history')
    op.drop_index(op.f('ix_balance_history_document_content_id'), table_name='balance_history')
    op.drop_index(op.f('ix_balance_history_branch_id'), table_name='balance_history')
    op.drop_table('balance_history')
    op.drop_index(op.f('ix_order_contents_staff_id'), table_name='order_contents')
    op.drop_index(op.f('ix_order_contents_room_table_order_id'), table_name='order_contents')
    op.drop_index(op.f('ix_order_contents_profile_menu_item_id'), table_name='order_contents')
    op.drop_index(op.f('ix_order_contents_profile_id'), table_name='order_contents')
    op.drop_index('ix_order_contents_order', table_name='order_contents')
    op.drop_index('ix_order_contents_menu_item', table_name='order_contents')
    op.drop_index(op.f('ix_order_contents_create_date'), table_name='order_contents')
    op.drop_index(op.f('ix_order_contents_branch_id'), table_name='order_contents')
    op.drop_table('order_contents')
    op.drop_index(op.f('ix_order_content_removed_room_table_order_id'), table_name='order_content_removed')
    op.drop_index(op.f('ix_order_content_removed_profile_menu_item_id'), table_name='order_content_removed')
    op.drop_index(op.f('ix_order_content_removed_profile_id'), table_name='order_content_removed')
    op.drop_index(op.f('ix_order_content_removed_branch_id'), table_name='order_content_removed')
    op.drop_table('order_content_removed')
    op.drop_index(op.f('ix_menu_item_content_store_item'), table_name='menu_item_content')
    op.drop_index(op.f('ix_menu_item_content_profile'), table_name='menu_item_content')
    op.drop_index(op.f('ix_menu_item_content_menu_item'), table_name='menu_item_content')
    op.drop_index(op.f('ix_menu_item_content_branch_id'), table_name='menu_item_content')
    op.drop_table('menu_item_content')
    op.drop_index(op.f('ix_fiscal_receipt_history_receipt_id'), table_name='fiscal_receipt_history')
    op.drop_index(op.f('ix_fiscal_receipt_history_profile_id'), table_name='fiscal_receipt_history')
    op.drop_table('fiscal_receipt_history')
    op.drop_index(op.f('ix_document_contents_profile_id'), table_name='document_contents')
    op.drop_index(op.f('ix_document_contents_material_content_id'), table_name='document_contents')
    op.drop_index(op.f('ix_document_contents_fifo_state_id'), table_name='document_contents')
    op.drop_index(op.f('ix_document_contents_document_id'), table_name='document_contents')
    op.drop_index(op.f('ix_document_contents_branch_id'), table_name='document_contents')
    op.drop_table('document_contents')
    op.drop_index(op.f('ix_clients_cards_history_room_table_order_id'), table_name='clients_cards_history')
    op.drop_index(op.f('ix_clients_cards_history_profile_id'), table_name='clients_cards_history')
    op.drop_index(op.f('ix_clients_cards_history_menu_item_id'), table_name='clients_cards_history')
    op.drop_index(op.f('ix_clients_cards_history_create_date'), table_name='clients_cards_history')
    op.drop_index(op.f('ix_clients_cards_history_client_id'), table_name='clients_cards_history')
    op.drop_index(op.f('ix_clients_cards_history_branch_id'), table_name='clients_cards_history')
    op.drop_table('clients_cards_history')
    op.drop_index(op.f('ix_order_payment_history_profile_id'), table_name='order_payment_history')
    op.drop_index(op.f('ix_order_payment_history_order_id'), table_name='order_payment_history')
    op.drop_table('order_payment_history')
    op.drop_index(op.f('ix_menu_items_profile'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_group'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_branch_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_fiscal_receipt_profile_id'), table_name='fiscal_receipt')
    op.drop_index(op.f('ix_fiscal_receipt_order_id'), table_name='fiscal_receipt')
    op.drop_table('fiscal_receipt')
    op.drop_index(op.f('ix_documents_type_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_profile_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_order_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_branch_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_orders_room_table_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_profile_staff_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_profile_id'), table_name='orders')
    op.drop_index('ix_orders_profile_date_paid', table_name='orders')
    op.drop_index(op.f('ix_orders_order_create_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_branch_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_menu_group_profile'), table_name='menu_group')
    op.drop_index(op.f('ix_menu_group_place'), table_name='menu_group')
    op.drop_index(op.f('ix_menu_group_branch_id'), table_name='menu_group')
    op.drop_table('menu_group')
    op.drop_index(op.f('ix_fifo_state_profile_id'), table_name='fifo_state')
    op.drop_index(op.f('ix_fifo_state_branch_id'), table_name='fifo_state')
    op.drop_table('fifo_state')
    op.drop_index(op.f('ix_tables_profile_id'), table_name='tables')
    op.drop_index(op.f('ix_tables_hall_id'), table_name='tables')
    op.drop_index(op.f('ix_tables_branch_id'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_store_language_profile_id'), table_name='store_language')
    op.drop_table('store_language')
    op.drop_index(op.f('ix_menu_place_profile'), table_name='menu_place')
    op.drop_index(op.f('ix_menu_place_branch_id'), table_name='menu_place')
    op.drop_table('menu_place')
    op.drop_index(op.f('ix_material_language_profile_id'), table_name='material_language')
    op.drop_index(op.f('ix_material_language_material_id'), table_name='material_language')
    op.drop_table('material_language')
    op.drop_index(op.f('ix_material_content_unit_id'), table_name='material_content')
    op.drop_index(op.f('ix_material_content_profile_id'), table_name='material_content')
    op.drop_index(op.f('ix_material_content_material_id'), table_name='material_content')
    op.drop_table('material_content')
    op.drop_index(op.f('ix_stores_profile_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_branch_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_measurements_lng_unit_id'), table_name='measurements_lng')
    op.drop_index(op.f('ix_measurements_lng_profile_id'), table_name='measurements_lng')
    op.drop_table('measurements_lng')
    op.drop_index(op.f('ix_materials_profile_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_material_category_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_material_category_language_profile_id'), table_name='material_category_language')
    op.drop_index(op.f('ix_material_category_language_material_category_id'), table_name='material_category_language')
    op.drop_table('material_category_language')
    op.drop_index(op.f('ix_logs_user_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_profile_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_date'), table_name='logs')
    op.drop_index(op.f('ix_logs_branch_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_halls_profile_id'), table_name='halls')
    op.drop_index(op.f('ix_halls_branch_id'), table_name='halls')
    op.drop_table('halls')
    op.drop_index(op.f('ix_document_type_template_profile_id'), table_name='document_type_template')
    op.drop_index(op.f('ix_document_type_template_document_type_id'), table_name='document_type_template')
    op.drop_table('document_type_template')
    op.drop_index(op.f('ix_client_cards_profile_id'), table_name='client_cards')
    op.drop_index(op.f('ix_client_cards_client_id'), table_name='client_cards')
    op.drop_table('client_cards')
    op.drop_index(op.f('ix_cashboxes_profile_id'), table_name='cashboxes')
    op.drop_index(op.f('ix_cashboxes_branch_id'), table_name='cashboxes')
    op.drop_table('cashboxes')
    op.drop_index(op.f('ix_break_points_profile_id'), table_name='break_points')
    op.drop_index(op.f('ix_break_points_branch_id'), table_name='break_points')
    op.drop_table('break_points')
    op.drop_index(op.f('ix_users_profile_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_staff_profile_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_migrations_column_map_table_map_id'), table_name='column_map', schema='migrations')
    op.drop_table('column_map', schema='migrations')
    op.drop_index(op.f('ix_measurements_profile_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_material_category_profile_id'), table_name='material_category')
    op.drop_table('material_category')
    op.drop_index(op.f('ix_document_types_profile_id'), table_name='document_types')
    op.drop_table('document_types')
    op.drop_index(op.f('ix_clients_profile_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_branches_profile_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_translate_string'), table_name='translate')
    op.drop_table('translate')
    op.drop_table('profiles')
    op.drop_table('table_map', schema='migrations')
    op.execute("DROP SCHEMA IF EXISTS migrations")
    # ### end Alembic commands ###
